### ISSUE TITLE
Why no table style

### ISSUE THREAD

**Issue by narukeh** [susam/spcss#6]
a table without a simple style looks really dumb. So why not have at least sth as simple as this:

```css
table, th, td {
  border: 1px solid #aaa;
  border-collapse: collapse;
  overflow: auto;
  padding: 2px 5px;
}
```
![pic-selected-201227-0300-07](https://user-images.githubusercontent.com/62762955/103162357-80de4580-47e7-11eb-9d50-9e50880d3ec7.png)

-----
(And btw, do you happen to know why firefox does not respect the theme i chose? Its not just with your `index.html` , its with all. I have chosen the dark theme, though websites still offer me the light verions)
